name: "Hello Action"
description: "Say Hello to my leetle friend terraform"
author: "eric.odell@ucop.edu"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "UCOP"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
